server:
  port: 8889
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.254.245:3306/yidian_oms?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: yidian
    password: Z%oYiT$IX4cm

mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID




